
CREATE TABLE [dbo].[SYS_RECLAMACAO_ORIGEM](
	[COD_ORIGEM] [int] IDENTITY(1,1) NOT NULL,
	[DESC_ORIGEM] [varchar](100) NOT NULL,
 CONSTRAINT [SYS_RECLAMACAO_ORIGEM_pk] PRIMARY KEY CLUSTERED 
(
	[COD_ORIGEM] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


