

CREATE TABLE [dbo].[SYS_RECLAMACAO_RESPONSAVEL](
	[COD_RESPONSAVEL] [tinyint] IDENTITY(1,1) NOT NULL,
	[DESC_RESPONSAVEL] [varchar](50) NOT NULL,
 CONSTRAINT [SYS_RECLAMACAO_RESPONSAVEL_pk] PRIMARY KEY CLUSTERED 
(
	[COD_RESPONSAVEL] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


