

CREATE TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL](
	[COD_RECLAMACAO] [int] IDENTITY(1,1) NOT NULL,
	[NOME_CLIENTE] [varchar](100) NOT NULL,
	[CPF_CLIENTE] [bigint] NOT NULL,
	[DATA_CADASTRO] [date] NOT NULL,
	[DATA_PRAZO] [date] NOT NULL,
	[DATA_USE_SYS] [date] NOT NULL,
	[HORA_USE_SYS] [time](0) NOT NULL,
	[COD_ORIGEM] [int] NOT NULL,
	[PROTOCOLO_RECLAMACAO] [bigint] NOT NULL,
	[DDD_RECLAMACAO] [int] NOT NULL,
	[FONE_RECLAMACAO] [int] NOT NULL,
	[COD_VIA] [int] NOT NULL,
	[COD_RESPONSAVEL] [tinyint] NOT NULL,
	[COD_OPERADOR] [bigint] NOT NULL,
	[FINALIZADO] [tinyint] NOT NULL,
	[OPERACAO] [varchar](30) NOT NULL,
 CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_pk] PRIMARY KEY CLUSTERED 
(
	[COD_RECLAMACAO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL]  WITH CHECK ADD  CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_SYS_RECLAMACAO_ORIGEM] FOREIGN KEY([COD_ORIGEM])
REFERENCES [dbo].[SYS_RECLAMACAO_ORIGEM] ([COD_ORIGEM])
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL] CHECK CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_SYS_RECLAMACAO_ORIGEM]
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL]  WITH CHECK ADD  CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_SYS_RECLAMACAO_RESPONSAVEL] FOREIGN KEY([COD_RESPONSAVEL])
REFERENCES [dbo].[SYS_RECLAMACAO_RESPONSAVEL] ([COD_RESPONSAVEL])
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL] CHECK CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_SYS_RECLAMACAO_RESPONSAVEL]
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL]  WITH CHECK ADD  CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_SYS_RECLAMACAO_VIA] FOREIGN KEY([COD_VIA])
REFERENCES [dbo].[SYS_RECLAMACAO_VIA] ([COD_VIA])
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_PRINCIPAL] CHECK CONSTRAINT [SYS_RECLAMACAO_PRINCIPAL_SYS_RECLAMACAO_VIA]
GO


