
CREATE TABLE [dbo].[SYS_RECLAMACAO_OBS](
	[COD_OBSERVACAO] [int] IDENTITY(1,1) NOT NULL,
	[COD_RECLAMACAO] [int] NOT NULL,
	[TEXT_OBSERVACAO] [varchar](500) NOT NULL,
 CONSTRAINT [SYS_RECLAMACAO_OBS_pk] PRIMARY KEY CLUSTERED 
(
	[COD_OBSERVACAO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_OBS]  WITH CHECK ADD  CONSTRAINT [SYS_RECLAMACAO_OBS_SYS_RECLAMACAO_PRINCIPAL] FOREIGN KEY([COD_RECLAMACAO])
REFERENCES [dbo].[SYS_RECLAMACAO_PRINCIPAL] ([COD_RECLAMACAO])
GO

ALTER TABLE [dbo].[SYS_RECLAMACAO_OBS] CHECK CONSTRAINT [SYS_RECLAMACAO_OBS_SYS_RECLAMACAO_PRINCIPAL]
GO


