/****** Object:  View [dbo].[VW_SYS_SERVDESK_COMPLETO]    Script Date: 31/08/2021 21:58:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_SYS_SERVDESK_COMPLETO]
AS
SELECT EVE.COD_EVENTO
	,EVE.[STATUS]
	,EVE.COD_SOLICITACAO
	,EVE.DATAHORA
	,EVE.OPERADOR_ORIGEM
	,EVE.COD_SETOR
	,EVE.COD_ABA
	,EVE.COD_TABULACAO
	,EVE.COD_MOTIVO
	,EVE.COD_EVENTO_ORIGEM
	,EVE.DATAHORA_FINAL
	,EVE.OPERADOR_FINAL
	,SDE.DESCRICAO AS 'SYS_STATUS_DESCRICAO'
	,FIC.COD_CLIENTE
	,SOL.COD_OPERACAO
	,SOL.NR_SYS_VENDAS
	,SOL.COD_TIPO_CONTRATO
	,SOL.COD_CONVENIO_OPERACAO
	,SOL.DATA_VENDA
	--,DBO.FN_GETDIAUTILDIFFDAY(SOL.DATA_VENDA, CAST(GETDATE() AS DATE))+1 AS 'VENDA_DIAS_UTEIS'
	,(DATEDIFF(dd, SOL.DATA_VENDA, GETDATE()) + 1) - (DATEDIFF(wk, SOL.DATA_VENDA, GETDATE()) * 2) - (
		CASE 
			WHEN DATENAME(dw, SOL.DATA_VENDA) = 'Sunday'
				THEN 1
			ELSE 0
			END
		) - (
		CASE 
			WHEN DATENAME(dw, GETDATE()) = 'Saturday'
				THEN 1
			ELSE 0
			END
		) AS 'VENDA_DIAS_UTEIS'
	,SOL.VENDEDOR
	,CLI.CPF
	,CLI.NOME
	,CLI.NASC
	,PES.VALOR_RENDA
	,PES.SEXO
	,PES.DOCUMENTO
	,PES.DOCUMENTO_UF
	,PES.DOCUMENTO_DATA
	,PES.DOCUMENTO_ORGAO
	,ADR.TP_LOGRADOURO AS 'CLI_TP_LOGRADOURO'
	,ADR.LOGRADOURO AS 'CLI_LOGRADOURO'
	,ADR.NUMERO AS 'CLI_NUMERO'
	,ADR.COMPLEMENTO AS 'CLI_COMPLEMENTO'
	,ADR.BAIRRO AS 'CLI_BAIRRO'
	,ADR.CEP AS 'CLI_CEP'
	,ADR.CIDADE AS 'CLI_CIDADE'
	,ADR.ESTADO AS 'CLI_ESTADO'
	,ADR.PONTO_REF AS 'CLI_PONTO_REF'
	,ADR.COD_MUN AS 'CLI_COD_MUN'
	,FON.DDD
	,FON.FONE
	,FON.DDD2
	,FON.FONE2
	,FON.DDD3
	,FON.FONE3
	,FON.DDD4
	,FON.FONE4
	,TPC.DESCRICAO AS 'SOL_TP_DESCRICAO'
	,SEN.TP_LOGRADOURO AS 'SOL_TP_LOGRADOURO'
	,SEN.LOGRADOURO AS 'SOL_LOGRADOURO'
	,SEN.NUMERO AS 'SOL_NUMERO'
	,SEN.COMPLEMENTO AS 'SOL_COMPLEMENTO'
	,SEN.BAIRRO AS 'SOL_BAIRRO'
	,SEN.CEP AS 'SOL_CEP'
	,SEN.CIDADE AS 'SOL_CIDADE'
	,SEN.ESTADO AS 'SOL_ESTADO'
	,SEN.PONTO_REF AS 'SOL_PONTO_REF'
	,SEN.COD_MUN AS 'SOL_COD_MUN'
	,SEN.EMAIL AS 'SOL_EMAIL'
	,OPE.OPERACAO
	,OPE.BANCO_DADOS
	,OPE.COD_BANCO
	,BCO.DESCRICAO
	,CON.COD_CONVENIO
	,CON.DESC_CONVENIO
	,SWS.NOME_AGENTE_DIGITACAO
	,SWS.CPF_AGENTE_DIGITACAO
	,SWS.WS
	,SWS.VL_IOF
	,SWS.COD_ORGAO_CONVENIO
	,ORG.COD_CONVENIO AS 'SOL_ORGAOS_CONVENIO'
	,ORG.COD_ORGAO
	,ORG.DESC_ORGAO
	,MAT.MATRICULA
	,MAT.MATRICULA_INSTITUIDOR
	,MAT.MATRICULA_UF
	,MAT.SENHA_MAT
	,MAT.ESPECIE
	,MAT.MARGEM
	,BAN.AGENCIA_PG
	,BAN.CONTA_PG
	,BAN.COD_BANCO_PG
	,BAN.TP_CONTA_PG
	,BAN.COMP_TP_PAGAMENTO_PG
	,BAN.AGENCIA_CONV
	,BAN.CONTA_CONV
	,BAN.COD_BANCO_CONV
	,BAN.TP_CONTA_CONV
	,BAN.COMP_TP_PAGAMENTO_CONV
	,BAN.TP_RECEBIMENTO_CONV
	,DVA.PROPOSTA_DIGITACAO
	,DVA.PARCELA_DIGITACAO
	,DVA.BRUTO_DIGITACAO
	,DVA.DIVIDA_DIGITACAO
	,DVA.LIQUIDO_DIGITACAO
	,DVA.PRAZO_DIGITACAO
	,DVA.TP_TABELA_DIGITACAO
	,DVA.COD_TABELA_DIGITACAO
	,DVA.TAXA_DIGITACAO
	,DVA.NASC_DIGITACAO
	,VAL.NR_CONTRATO
	,VAL.VL_PARC
	,VAL.VL_PARC_ANTIGA
	,VAL.VL_BRUTO
	,VAL.VL_DIVIDA
	,VAL.VL_TROCO
	,VAL.QTD_PARC
	,VAL.VL_SEGURO
	,VAL.TABELA
	,VAL.TAXA
	,VAL.RAMAL
	,VAL.ORIGEM_DATA_RESPOSTA
	,VAL.ORIGEM_CORBAN
	,VAL.COMPRADO
	,VAL.BANCO_ASSINATURA
	,VAL.LOTE
	,VAL.PRE_SAQUE
	,CASE 
		WHEN VAL.FIDELIZADO = 1
			THEN 'Formalizado com sucesso'
		ELSE ''
		END AS FIDELIZADO
	,VAL.SENHA_AVERBACAO
	,EVI.COD_VISITA
	--,EVI.COD_ROTEIRO
	,ENV.COD_VIA
	,ENV.COD_TIPO_VISITA
	,ENV.DATA
	,ENV.DATA_FECHAMENTO
	,VIA.VIA
	,VST.DESCRICAO AS 'VIS_TIPO_DESCRICAO'
	,VSM.CNPJ_BASE
	,VSM.APELIDO_BASE
	,VSM.DATA_VISITA
	,CASE 
		WHEN VSM.PERIODO_VISITA = 'M'
			THEN 'MANHÃ'
		WHEN VSM.PERIODO_VISITA = 'T'
			THEN 'TARDE'
		WHEN VSM.PERIODO_VISITA = 'I'
			THEN 'INTEGRAL'
		ELSE VSM.PERIODO_VISITA
		END AS PERIODO_VISITA
	,VSM.DATA_ORIGINAL_VISITA
	,VSM.ROGO
	,VSC.AR
	,AIN.PROPOSTA_DIGITACAO AS 'PROPOSTA_INTEGRADO'
	,AIN.DATA_INTEGRACAO
	,TAB.DESCRICAO AS 'TABULACAO_DESCRICAO'
	,MOT.DESCRICAO AS 'MOTIVO_DESCRICAO'
	,VSC.AR_RETORNO
	--,REV.NUMERO_LOGISTICA_REVERSA
	--,LRE.NUMERO_OBJETO
	,APP_CKL_PROTOCOLO_BANCO.PROTOCOLO PROTOCOLO_BANCO
	,PRO.[SITUACAO] AS SIT_PANCRED
	,VIP.AR_VIPP
	,RES.STATUS_POSTAGEM_VIPP
	,RES.DATAHORA_STATUS_VIPP
	,EVE_VIS.COD_VISITA AS REF_COD_VISITA
	,ISNULL(EVE_VIS_D.DATA_VISITA, SOL.DATA_VENDA) AS REF_DATA_VISITA
	,CLI_WHATSAPP.DDD_FONE_WHATSAPP
	,CLI_WHATSAPP.FONE_WHATSAPP
	,CLI_FL_CORRENTISTA.FL_CORRENTISTA
	,PRO.STATUS_ASSINATURA
	,PRO.DESCRICAO_ATIVIDADE
	--,SOL_DADOS_PORTOCRED.CLASSE_PROFISSIONAL
	--,SOL_DADOS_PORTOCRED.ATIVIDADE
	--,SOL_DADOS_PORTOCRED.ESTADO_CIVIL
	--,SOL_DADOS_PORTOCRED.NACIONALIDADE
	--,SOL_DADOS_PORTOCRED.GRAU_INSTRUCAO
	--,SOL_DADOS_PORTOCRED.NOME_MAE
	--,SOL_DADOS_PORTOCRED.CIDADE_NASC
	--,SOL_DADOS_PORTOCRED.UF_NASC
	--,SOL_DADOS_PORTOCRED.NOME_REF_1
	--,SOL_DADOS_PORTOCRED.RELACIONAMENTO_REF_1
	--,SOL_DADOS_PORTOCRED.DDD_REF_1
	--,SOL_DADOS_PORTOCRED.FONE_REF_1
	--,SOL_DADOS_PORTOCRED.NOME_REF_2
	--,SOL_DADOS_PORTOCRED.RELACIONAMENTO_REF_2
	--,SOL_DADOS_PORTOCRED.DDD_REF_2
	--,SOL_DADOS_PORTOCRED.FONE_REF_2
	,DVA.RENDA_BRUTA
	,DVA.DATA_VENCIMENTO
	,VSM.EMAIL_BASE
	,SOL_CONSULTA_HIST_FIN_EPF.FASE FASE_DIGITAL_SAFRA
	,SOL_CONSULTA_HIST_FIN_EPF.DATAHORA_FASE DATA_FASE_DIGITAL
	,SOL_CONSULTA_WS_EPF.SITUACAO_CONTRATO
	,SOL_CONSULTA_WS_EPF.STATUS_EPF
	,SOL_WS_BANRISUL.SIT_BANRISUL
	,SOL_WS_BANRISUL.STATUS_BANRISUL
	,SOL_WS_BANRISUL.DATA_INCLUSAO_BANRISUL
	,DATEDIFF(DAY, SOL.DATA_VENDA, GETDATE()) AS 'CONTADOR_DATA_VENDA'
	,DATEDIFF(MINUTE, SOL.DATA_VENDA, GETDATE()) AS 'CONTADOR_MINUTOS_DATA_VENDA'
	,DATEDIFF(DAY, EVE.DATAHORA, GETDATE()) AS 'CONTADOR_DATA_EVENTO'
	,ETASAFRA.DESCRICAO AS 'ETAPA_DIGITAL'
	,MOTSAFRA.DESCRICAO AS 'MOTIVO_DIGITAL'
	,SOL_VINCULO_WHATSAPP.VINCULO_WHATSAPP
	,CONVERT(VARCHAR(19), SOL_CONSULTA_WS_EPF.DATAHORA_CONSULTA, 121) AS 'DATAHORA_CONSULTA_STATUS_EPF'
	,CASE 
		WHEN VAL.ADEQUACAO_MARGEM = 1
			THEN 'SIM'
		WHEN VAL.ADEQUACAO_MARGEM = 0
			THEN 'NÃO'
		ELSE NULL
		END AS ADEQUACAO_MARGEM
	,VAL.BANCO_COMPRADO
	,FAI.DESC_FAIXA AS FAIXA_PREDITIVO
FROM SYS_EVENTOS EVE(NOLOCK)
LEFT JOIN SYS_STATUS_DESCRICAO SDE(NOLOCK) ON EVE.[STATUS] = SDE.[STATUS]
LEFT JOIN SYS_SOLICITACAO_FICHA FIC(NOLOCK) ON FIC.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN SOL_SOLICITACOES SOL(NOLOCK) ON SOL.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN SOL_TP_CONTRATO TPC(NOLOCK) ON SOL.COD_TIPO_CONTRATO = TPC.COD_TIPO_CONTRATO
LEFT JOIN SOL_ENDERECO SEN(NOLOCK) ON SOL.COD_SOLICITACAO = SEN.COD_SOLICITACAO
LEFT JOIN SOL_OPERACAO OPE(NOLOCK) ON SOL.COD_OPERACAO = OPE.COD_OPERACAO
LEFT JOIN SOL_BANCOS BCO(NOLOCK) ON OPE.COD_BANCO = BCO.COD_BANCO
LEFT JOIN SOL_CONVENIOS CON(NOLOCK) ON CON.COD_CONVENIO_OPERACAO = SOL.COD_CONVENIO_OPERACAO
LEFT JOIN SOL_WS SWS(NOLOCK) ON SOL.COD_SOLICITACAO = SWS.COD_SOLICITACAO
LEFT JOIN SOL_ORGAOS ORG(NOLOCK) ON SWS.COD_ORGAO_CONVENIO = ORG.COD_ORGAO_CONVENIO
LEFT JOIN SOL_MATRICULAS MAT(NOLOCK) ON SOL.COD_SOLICITACAO = MAT.COD_SOLICITACAO
LEFT JOIN SOL_BANCARIOS BAN(NOLOCK) ON SOL.COD_SOLICITACAO = BAN.COD_SOLICITACAO
LEFT JOIN SOL_DIG_VALORES DVA(NOLOCK) ON SOL.COD_SOLICITACAO = DVA.COD_SOLICITACAO
LEFT JOIN SOL_VALORES VAL(NOLOCK) ON SOL.COD_SOLICITACAO = VAL.COD_SOLICITACAO
LEFT JOIN CLI_CLIENTE CLI(NOLOCK) ON FIC.COD_CLIENTE = CLI.COD_CLIENTE
LEFT JOIN CLI_PESSOAIS PES(NOLOCK) ON FIC.COD_CLIENTE = PES.COD_CLIENTE
LEFT JOIN CLI_ENDERECO ADR(NOLOCK) ON FIC.COD_CLIENTE = ADR.COD_CLIENTE
LEFT JOIN CLI_FONES FON(NOLOCK) ON FIC.COD_CLIENTE = FON.COD_CLIENTE
LEFT JOIN (
	SELECT MAX(EVI.COD_VISITA) COD_VISITA
		,EVI.COD_SOLICITACAO
	FROM APP_VIS_EVENTO_VISITA EVI(NOLOCK)
	GROUP BY EVI.COD_SOLICITACAO
	) EVI ON EVE.COD_SOLICITACAO = EVI.COD_SOLICITACAO
LEFT JOIN APP_VIS_ENVIO ENV(NOLOCK) ON EVI.COD_VISITA = ENV.COD_VISITA
LEFT JOIN APP_VIS_VIA VIA(NOLOCK) ON ENV.COD_VIA = VIA.COD_VIA
LEFT JOIN APP_VIS_TIPO VST(NOLOCK) ON ENV.COD_TIPO_VISITA = VST.COD_TIPO_VISITA
LEFT JOIN APP_VIS_MOTOBOY VSM(NOLOCK) ON EVI.COD_VISITA = VSM.COD_VISITA
LEFT JOIN APP_VIS_CORREIO VSC(NOLOCK) ON EVI.COD_VISITA = VSC.COD_VISITA
LEFT JOIN APP_INT_INTEGRACAO AIN(NOLOCK) ON EVE.COD_EVENTO = AIN.COD_EVENTO
	AND EVE.COD_SOLICITACAO = AIN.COD_SOLICITACAO
LEFT JOIN APP_TAB_TABULACOES TAB(NOLOCK) ON EVE.COD_TABULACAO = TAB.COD_TABULACAO
LEFT JOIN APP_TAB_MOTIVOS MOT(NOLOCK) ON EVE.COD_MOTIVO = MOT.COD_MOTIVO
--LEFT JOIN (
--	SELECT *
--		,ROW_NUMBER() OVER (
--			PARTITION BY COD_SOLICITACAO ORDER BY DATAHORA DESC
--			) ORDEM
--	FROM APP_LOG_LOGISTICA_REVERSA REV(NOLOCK)
--	) REV ON REV.ORDEM = 1
--	AND EVE.COD_SOLICITACAO = REV.COD_SOLICITACAO
--LEFT JOIN APP_LOG_REVERSO_VISITA LRE(NOLOCK) ON LRE.NUMERO_LOGISTICA_REVERSA = REV.NUMERO_LOGISTICA_REVERSA
LEFT JOIN APP_CKL_PROTOCOLO_BANCO(NOLOCK) ON APP_CKL_PROTOCOLO_BANCO.COD_EVENTO = EVE.COD_EVENTO
LEFT JOIN [APP_ROB_PROPOSTAS_SITUACAO_PANCRED] PRO(NOLOCK) ON PRO.PROPOSTA = SUBSTRING(DVA.PROPOSTA_DIGITACAO, 1, 9)
LEFT JOIN VW_APP_VIPP_AR VIP ON VIP.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN [dbo].VW_APP_VIPP_STATUS RES(NOLOCK) ON VIP.AR_VIPP = RES.AR_VIPP
LEFT JOIN SYS_EVENTO_VISITA EVE_VIS(NOLOCK) ON EVE_VIS.COD_EVENTO = EVE.COD_EVENTO
LEFT JOIN APP_VIS_MOTOBOY EVE_VIS_D(NOLOCK) ON EVE_VIS.COD_VISITA = EVE_VIS_D.COD_VISITA
LEFT JOIN CLI_WHATSAPP(NOLOCK) ON CLI_WHATSAPP.COD_CLIENTE = CLI.COD_CLIENTE
LEFT JOIN CLI_FL_CORRENTISTA(NOLOCK) ON CLI_FL_CORRENTISTA.COD_CLIENTE = CLI.COD_CLIENTE
--LEFT JOIN SOL_DADOS_PORTOCRED(NOLOCK) ON SOL_DADOS_PORTOCRED.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN SOL_CONSULTA_HIST_FIN_EPF(NOLOCK) ON SOL_CONSULTA_HIST_FIN_EPF.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN SOL_CONSULTA_WS_EPF(NOLOCK) ON SOL_CONSULTA_WS_EPF.COD_SOLICITACAO = EVE.COD_SOLICITACAO
	AND SOL_CONSULTA_WS_EPF.[PROPOSTA_DIGITACAO] = DVA.[PROPOSTA_DIGITACAO]
LEFT JOIN SOL_WS_BANRISUL(NOLOCK) ON SOL_WS_BANRISUL.COD_SOLICITACAO = EVE.COD_SOLICITACAO
	AND SOL_WS_BANRISUL.[PROPOSTA_DIGITACAO] = DVA.[PROPOSTA_DIGITACAO]
LEFT JOIN SOL_FORMALIZACAO_DIGITAL(NOLOCK) ON SOL_FORMALIZACAO_DIGITAL.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN APP_TAB_TABULACOES ETASAFRA(NOLOCK) ON ETASAFRA.COD_TABULACAO = SOL_FORMALIZACAO_DIGITAL.ETAPA
	AND ETASAFRA.COD_TABULACAO >= 446
LEFT JOIN APP_TAB_MOTIVOS MOTSAFRA(NOLOCK) ON MOTSAFRA.COD_MOTIVO = SOL_FORMALIZACAO_DIGITAL.MOTIVO
	AND MOTSAFRA.COD_MOTIVO > 0
LEFT JOIN SOL_VINCULO_WHATSAPP(NOLOCK) ON SOL_VINCULO_WHATSAPP.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN SOL_VINCULO_FAIXA SOF(NOLOCK) ON SOF.COD_SOLICITACAO = EVE.COD_SOLICITACAO
LEFT JOIN FAX_FAIXA FAI(NOLOCK) ON FAI.COD_FAIXA = SOF.COD_FAIXA
WHERE EVE.STATUS = 0
GO


